### ISSUE TITLE
mobile

### ISSUE THREAD

**Issue by zaycode** [tolgee/dart-example#1]
this work fine on mobile?

**Comment by JanCizmar** [comment]
It doesn't. It's currently just a wrapper for JS integrations.

**Comment by zaycode** [comment]
Hello @JanCizmar thanks for replay.
 my client has used tolgee provider for translation, because tolgee not support yet on dart mobile  is there any option to get json so i can combined it with [easy_localization](https://pub.dev/packages/easy_localization)
 thanks

**Comment by JanCizmar** [comment]
Hey, you can export the data to`.json` in the export section of the platform.

**Comment by zaycode** [comment]
@JanCizmar so we cannot  direct access  from your platform?, ex: tolgee.com/$key/language/en.json

**Comment by JanCizmar** [comment]
The export calls this [API endpoint](https://tolgee.io/api#tag/Export/operation/export_1), or you can also use [this one](https://tolgee.io/api#tag/Translations/operation/getAllTranslations_1) which also returns data in json format.
